name: my_idea_pool
description: My Idea Pool / Arc Small Project

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2020.07.24+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^0.5.8
  rxdart: ^0.24.1
  equatable: ^1.2.2
  flutter_bloc: ^6.0.1
  http: ^0.12.2
  uuid: ^2.2.0
  logger: ^0.9.1
  flutter_form_builder: ^3.11.6

  awesome_dialog: ^1.1.3
  flutter_spinkit: ^4.1.2+1
  #progress_dialog: ^1.2.4
  progress_dialog:
    #path: ../../flutter-open-forks/progress_dialog
    git: git://github.com/beerstorm-net/progress_dialog.git
  #jiffy: ^3.0.1
  jiffy:
    #path: ../../flutter-open-forks/jiffy/
    git: git://github.com/beerstorm-net/jiffy.git

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_launcher_icons: ^0.7.5
  flutter_test:
    sdk: flutter

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app_icon.jpg"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/config/
    - assets/images/
